export const ARTICLE_SOURCE_ADD_REQ = 'ARTICLE_SOURCE_ADD_REQ';
export const ARTICLE_SOURCE_ADD_RSP = 'ARTICLE_SOURCE_ADD_RSP';

export const ARTICLE_SOURCE_LIST_REQ = 'ARTICLE_SOURCE_LIST_REQ';
export const ARTICLE_SOURCE_LIST_RSP = 'ARTICLE_SOURCE_LIST_RSP';

export const ARTICLE_SOURCE_DELETE_BY_ID_REQ = 'ARTICLE_SOURCE_DELETE_BY_ID_REQ';
export const ARTICLE_SOURCE_DELETE_BY_ID_RSP = 'ARTICLE_SOURCE_DELETE_BY_ID_RSP';


