export const TAG_ADD_REQUEST = 'TAG_ADD_REQUEST';
export const TAG_ADD_RESPONSE = 'TAG_ADD_RESPONSE';

export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_RESPONSE = 'TAG_LIST_RESPONSE';