export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_RSP = 'USER_LOGIN_RSP';

export const USER_FINDBYMOBILE_REQ = 'USER_FINDBYMOBILE_REQ';
export const USER_FINDBYMOBILE_RSP = 'USER_FINDBYMOBILE_RSP';

